auth:
  enabled: false
  providers:
    - label: "Auth0"
      type: oidc
      issuer: https://qovery-dx.eu.auth0.com
      client_id: EEw4pOSjKfyQqq6f3HlIzvM4zFzj87Ou
      client_secret: XDHwPCKYdN2rftMk-31m-n-xOQidgmexMuxZy75zvOIX4a-8R25f8ipFHg21UW1v
      scope: openid profile email
      audience: temporal 
      callback_base_uri: https://z5bc91407-zcebc546b-gtw.z2718d196.jvm.world
      pass_id_token: false
